# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.MEC013_location.distance_notification_subscription import DistanceNotificationSubscription  # noqa: F401,E501
from swagger_server import util


class DistanceSubscriptionIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, distance_notification_subscription: DistanceNotificationSubscription=None):  # noqa: E501
        """DistanceSubscriptionIdBody - a model defined in Swagger

        :param distance_notification_subscription: The distance_notification_subscription of this DistanceSubscriptionIdBody.  # noqa: E501
        :type distance_notification_subscription: DistanceNotificationSubscription
        """
        self.swagger_types = {
            'distance_notification_subscription': DistanceNotificationSubscription
        }

        self.attribute_map = {
            'distance_notification_subscription': 'distanceNotificationSubscription'
        }
        self._distance_notification_subscription = distance_notification_subscription

    @classmethod
    def from_dict(cls, dikt) -> 'DistanceSubscriptionIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The distance_subscriptionId_body of this DistanceSubscriptionIdBody.  # noqa: E501
        :rtype: DistanceSubscriptionIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def distance_notification_subscription(self) -> DistanceNotificationSubscription:
        """Gets the distance_notification_subscription of this DistanceSubscriptionIdBody.


        :return: The distance_notification_subscription of this DistanceSubscriptionIdBody.
        :rtype: DistanceNotificationSubscription
        """
        return self._distance_notification_subscription

    @distance_notification_subscription.setter
    def distance_notification_subscription(self, distance_notification_subscription: DistanceNotificationSubscription):
        """Sets the distance_notification_subscription of this DistanceSubscriptionIdBody.


        :param distance_notification_subscription: The distance_notification_subscription of this DistanceSubscriptionIdBody.
        :type distance_notification_subscription: DistanceNotificationSubscription
        """

        self._distance_notification_subscription = distance_notification_subscription
