# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401 # pylint: disable=unused-import

from typing import List, Dict  # noqa: F401 # pylint: disable=unused-import

from swagger_server.models.base_model_ import Model
from swagger_server.models.MEC013_location.access_point_list import \
	AccessPointList  # noqa: F401 # pylint: disable=unused-import,E501
from swagger_server import util


class InlineResponse2004(Model):
	"""NOTE: This class is auto generated by the swagger code generator program.

	Do not edit the class manually.
	"""

	def __init__(self, access_point_list: AccessPointList = None):  # noqa: E501
		"""InlineResponse2004 - a model defined in Swagger

		:param access_point_list: The access_point_list of this InlineResponse2004.  # noqa: E501
		:type access_point_list: AccessPointList
		"""
		self.swagger_types = {
			'access_point_list': AccessPointList
		}

		self.attribute_map = {
			'access_point_list': 'accessPointList'
		}
		self._access_point_list = access_point_list

	@classmethod
	def from_dict(cls, dikt) -> 'InlineResponse2004':
		"""Returns the dict as a model

		:param dikt: A dict.
		:type: dict
		:return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
		:rtype: InlineResponse2004
		"""
		return util.deserialize_model(dikt, cls)

	@property
	def access_point_list(self) -> AccessPointList:
		"""Gets the access_point_list of this InlineResponse2004.


		:return: The access_point_list of this InlineResponse2004.
		:rtype: AccessPointList
		"""
		return self._access_point_list

	@access_point_list.setter
	def access_point_list(self, access_point_list: AccessPointList):
		"""Sets the access_point_list of this InlineResponse2004.


		:param access_point_list: The access_point_list of this InlineResponse2004.
		:type access_point_list: AccessPointList
		"""

		self._access_point_list = access_point_list
