# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.MEC013_location.callback_reference import CallbackReference  # noqa: F401,E501
from swagger_server.models.MEC013_location.user_event_type import UserEventType  # noqa: F401,E501
from swagger_server import util


class UserTrackingSubscription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address: str=None, callback_reference: CallbackReference=None, client_correlator: str=None, resource_url: str=None, user_event_criteria: List[UserEventType]=None):  # noqa: E501
        """UserTrackingSubscription - a model defined in Swagger

        :param address: The address of this UserTrackingSubscription.  # noqa: E501
        :type address: str
        :param callback_reference: The callback_reference of this UserTrackingSubscription.  # noqa: E501
        :type callback_reference: CallbackReference
        :param client_correlator: The client_correlator of this UserTrackingSubscription.  # noqa: E501
        :type client_correlator: str
        :param resource_url: The resource_url of this UserTrackingSubscription.  # noqa: E501
        :type resource_url: str
        :param user_event_criteria: The user_event_criteria of this UserTrackingSubscription.  # noqa: E501
        :type user_event_criteria: List[UserEventType]
        """
        self.swagger_types = {
            'address': str,
            'callback_reference': CallbackReference,
            'client_correlator': str,
            'resource_url': str,
            'user_event_criteria': List[UserEventType]
        }

        self.attribute_map = {
            'address': 'address',
            'callback_reference': 'callbackReference',
            'client_correlator': 'clientCorrelator',
            'resource_url': 'resourceURL',
            'user_event_criteria': 'userEventCriteria'
        }
        self._address = address
        self._callback_reference = callback_reference
        self._client_correlator = client_correlator
        self._resource_url = resource_url
        self._user_event_criteria = user_event_criteria

    @classmethod
    def from_dict(cls, dikt) -> 'UserTrackingSubscription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserTrackingSubscription of this UserTrackingSubscription.  # noqa: E501
        :rtype: UserTrackingSubscription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this UserTrackingSubscription.

        Address of user (e.g. \"sip\" URI, \"tel\" URI, \"acr\" URI) to monitor  # noqa: E501

        :return: The address of this UserTrackingSubscription.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this UserTrackingSubscription.

        Address of user (e.g. \"sip\" URI, \"tel\" URI, \"acr\" URI) to monitor  # noqa: E501

        :param address: The address of this UserTrackingSubscription.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def callback_reference(self) -> CallbackReference:
        """Gets the callback_reference of this UserTrackingSubscription.


        :return: The callback_reference of this UserTrackingSubscription.
        :rtype: CallbackReference
        """
        return self._callback_reference

    @callback_reference.setter
    def callback_reference(self, callback_reference: CallbackReference):
        """Sets the callback_reference of this UserTrackingSubscription.


        :param callback_reference: The callback_reference of this UserTrackingSubscription.
        :type callback_reference: CallbackReference
        """
        if callback_reference is None:
            raise ValueError("Invalid value for `callback_reference`, must not be `None`")  # noqa: E501

        self._callback_reference = callback_reference

    @property
    def client_correlator(self) -> str:
        """Gets the client_correlator of this UserTrackingSubscription.

        A correlator that the client can use to tag this particular resource representation during a request to create a resource on the server.  # noqa: E501

        :return: The client_correlator of this UserTrackingSubscription.
        :rtype: str
        """
        return self._client_correlator

    @client_correlator.setter
    def client_correlator(self, client_correlator: str):
        """Sets the client_correlator of this UserTrackingSubscription.

        A correlator that the client can use to tag this particular resource representation during a request to create a resource on the server.  # noqa: E501

        :param client_correlator: The client_correlator of this UserTrackingSubscription.
        :type client_correlator: str
        """

        self._client_correlator = client_correlator

    @property
    def resource_url(self) -> str:
        """Gets the resource_url of this UserTrackingSubscription.

        Self referring URL  # noqa: E501

        :return: The resource_url of this UserTrackingSubscription.
        :rtype: str
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url: str):
        """Sets the resource_url of this UserTrackingSubscription.

        Self referring URL  # noqa: E501

        :param resource_url: The resource_url of this UserTrackingSubscription.
        :type resource_url: str
        """

        self._resource_url = resource_url

    @property
    def user_event_criteria(self) -> List[UserEventType]:
        """Gets the user_event_criteria of this UserTrackingSubscription.

        List of user event values to generate notifications for (these apply to address specified). If this element is missing, a notification is requested to be generated for any change in user event.  # noqa: E501

        :return: The user_event_criteria of this UserTrackingSubscription.
        :rtype: List[UserEventType]
        """
        return self._user_event_criteria

    @user_event_criteria.setter
    def user_event_criteria(self, user_event_criteria: List[UserEventType]):
        """Sets the user_event_criteria of this UserTrackingSubscription.

        List of user event values to generate notifications for (these apply to address specified). If this element is missing, a notification is requested to be generated for any change in user event.  # noqa: E501

        :param user_event_criteria: The user_event_criteria of this UserTrackingSubscription.
        :type user_event_criteria: List[UserEventType]
        """

        self._user_event_criteria = user_event_criteria
