# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Rssi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rssi: int=None):  # noqa: E501
        """Rssi - a model defined in Swagger

        :param rssi: The rssi of this Rssi.  # noqa: E501
        :type rssi: int
        """
        self.swagger_types = {
            'rssi': int
        }

        self.attribute_map = {
            'rssi': 'rssi'
        }
        self._rssi = rssi

    @classmethod
    def from_dict(cls, dikt) -> 'Rssi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Rssi of this Rssi.  # noqa: E501
        :rtype: Rssi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rssi(self) -> int:
        """Gets the rssi of this Rssi.

        The Received Signal Strength Indicator from a station  # noqa: E501

        :return: The rssi of this Rssi.
        :rtype: int
        """
        return self._rssi

    @rssi.setter
    def rssi(self, rssi: int):
        """Sets the rssi of this Rssi.

        The Received Signal Strength Indicator from a station  # noqa: E501

        :param rssi: The rssi of this Rssi.
        :type rssi: int
        """
        if rssi is None:
            raise ValueError("Invalid value for `rssi`, must not be `None`")  # noqa: E501

        self._rssi = rssi
