# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401 # pylint: disable=unused-import

from typing import List, Dict  # noqa: F401 # pylint: disable=unused-import

from swagger_server.models.base_model_ import Model
from swagger_server.models.MEC011_service_management.end_point_info_uri import \
	EndPointInfoUri  # noqa: F401 # pylint: disable=unused-import,E501
from swagger_server import util


class EndPointInfoUris(Model):
	"""NOTE: This class is auto generated by the swagger code generator program.

	Do not edit the class manually.
	"""

	def __init__(self, uris: List[EndPointInfoUri] = None):  # noqa: E501
		"""EndPointInfoUris - a model defined in Swagger

		:param uris: The uris of this EndPointInfoUris.  # noqa: E501
		:type uris: List[EndPointInfoUri]
		"""
		self.swagger_types = {
			'uris': List[EndPointInfoUri]
		}

		self.attribute_map = {
			'uris': 'uris'
		}
		self._uris = uris

	@classmethod
	def from_dict(cls, dikt) -> 'EndPointInfoUris':
		"""Returns the dict as a model

		:param dikt: A dict.
		:type: dict
		:return: The EndPointInfo.Uris of this EndPointInfoUris.  # noqa: E501
		:rtype: EndPointInfoUris
		"""
		return util.deserialize_model(dikt, cls)

	@property
	def uris(self) -> List[EndPointInfoUri]:
		"""Gets the uris of this EndPointInfoUris.


		:return: The uris of this EndPointInfoUris.
		:rtype: List[EndPointInfoUri]
		"""
		return self._uris

	@uris.setter
	def uris(self, uris: List[EndPointInfoUri]):
		"""Sets the uris of this EndPointInfoUris.


		:param uris: The uris of this EndPointInfoUris.
		:type uris: List[EndPointInfoUri]
		"""
		if uris is None:
			raise ValueError("Invalid value for `uris`, must not be `None`")  # noqa: E501

		self._uris = uris
