# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransportType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    REST_HTTP = "REST_HTTP"
    MB_TOPIC_BASED = "MB_TOPIC_BASED"
    MB_ROUTING = "MB_ROUTING"
    MB_PUBSUB = "MB_PUBSUB"
    RPC = "RPC"
    RPC_STREAMING = "RPC_STREAMING"
    WEBSOCKET = "WEBSOCKET"
    def __init__(self):  # noqa: E501
        """TransportType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TransportType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransportType of this TransportType.  # noqa: E501
        :rtype: TransportType
        """
        return util.deserialize_model(dikt, cls)
