# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.MEC016_device_application_interface.location_constraints import LocationConstraints  # noqa: F401,E501
from swagger_server import util


class ApplicationContextUpdateNotificationUserAppInstanceInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, app_instance_id: str=None, app_location: LocationConstraints=None, reference_uri: str=None):  # noqa: E501
        """ApplicationContextUpdateNotificationUserAppInstanceInfo - a model defined in Swagger

        :param app_instance_id: The app_instance_id of this ApplicationContextUpdateNotificationUserAppInstanceInfo.  # noqa: E501
        :type app_instance_id: str
        :param app_location: The app_location of this ApplicationContextUpdateNotificationUserAppInstanceInfo.  # noqa: E501
        :type app_location: LocationConstraints
        :param reference_uri: The reference_uri of this ApplicationContextUpdateNotificationUserAppInstanceInfo.  # noqa: E501
        :type reference_uri: str
        """
        self.swagger_types = {
            'app_instance_id': str,
            'app_location': LocationConstraints,
            'reference_uri': str
        }

        self.attribute_map = {
            'app_instance_id': 'appInstanceId',
            'app_location': 'appLocation',
            'reference_uri': 'referenceURI'
        }
        self._app_instance_id = app_instance_id
        self._app_location = app_location
        self._reference_uri = reference_uri

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationContextUpdateNotificationUserAppInstanceInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationContextUpdateNotification_userAppInstanceInfo of this ApplicationContextUpdateNotificationUserAppInstanceInfo.  # noqa: E501
        :rtype: ApplicationContextUpdateNotificationUserAppInstanceInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_instance_id(self) -> str:
        """Gets the app_instance_id of this ApplicationContextUpdateNotificationUserAppInstanceInfo.

        Identifier of the user application instance.  # noqa: E501

        :return: The app_instance_id of this ApplicationContextUpdateNotificationUserAppInstanceInfo.
        :rtype: str
        """
        return self._app_instance_id

    @app_instance_id.setter
    def app_instance_id(self, app_instance_id: str):
        """Sets the app_instance_id of this ApplicationContextUpdateNotificationUserAppInstanceInfo.

        Identifier of the user application instance.  # noqa: E501

        :param app_instance_id: The app_instance_id of this ApplicationContextUpdateNotificationUserAppInstanceInfo.
        :type app_instance_id: str
        """

        self._app_instance_id = app_instance_id

    @property
    def app_location(self) -> LocationConstraints:
        """Gets the app_location of this ApplicationContextUpdateNotificationUserAppInstanceInfo.


        :return: The app_location of this ApplicationContextUpdateNotificationUserAppInstanceInfo.
        :rtype: LocationConstraints
        """
        return self._app_location

    @app_location.setter
    def app_location(self, app_location: LocationConstraints):
        """Sets the app_location of this ApplicationContextUpdateNotificationUserAppInstanceInfo.


        :param app_location: The app_location of this ApplicationContextUpdateNotificationUserAppInstanceInfo.
        :type app_location: LocationConstraints
        """

        self._app_location = app_location

    @property
    def reference_uri(self) -> str:
        """Gets the reference_uri of this ApplicationContextUpdateNotificationUserAppInstanceInfo.

        Address of the user application instance.  # noqa: E501

        :return: The reference_uri of this ApplicationContextUpdateNotificationUserAppInstanceInfo.
        :rtype: str
        """
        return self._reference_uri

    @reference_uri.setter
    def reference_uri(self, reference_uri: str):
        """Sets the reference_uri of this ApplicationContextUpdateNotificationUserAppInstanceInfo.

        Address of the user application instance.  # noqa: E501

        :param reference_uri: The reference_uri of this ApplicationContextUpdateNotificationUserAppInstanceInfo.
        :type reference_uri: str
        """

        self._reference_uri = reference_uri
