# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.MEC016_device_application_interface.location_constraints import LocationConstraints  # noqa: F401,E501
from swagger_server import util


class ApplicationLocationAvailabilityAppInfoAvailableLocations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, app_location: LocationConstraints=None):  # noqa: E501
        """ApplicationLocationAvailabilityAppInfoAvailableLocations - a model defined in Swagger

        :param app_location: The app_location of this ApplicationLocationAvailabilityAppInfoAvailableLocations.  # noqa: E501
        :type app_location: LocationConstraints
        """
        self.swagger_types = {
            'app_location': LocationConstraints
        }

        self.attribute_map = {
            'app_location': 'appLocation'
        }
        self._app_location = app_location

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationLocationAvailabilityAppInfoAvailableLocations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationLocationAvailability_appInfo_availableLocations of this ApplicationLocationAvailabilityAppInfoAvailableLocations.  # noqa: E501
        :rtype: ApplicationLocationAvailabilityAppInfoAvailableLocations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_location(self) -> LocationConstraints:
        """Gets the app_location of this ApplicationLocationAvailabilityAppInfoAvailableLocations.


        :return: The app_location of this ApplicationLocationAvailabilityAppInfoAvailableLocations.
        :rtype: LocationConstraints
        """
        return self._app_location

    @app_location.setter
    def app_location(self, app_location: LocationConstraints):
        """Sets the app_location of this ApplicationLocationAvailabilityAppInfoAvailableLocations.


        :param app_location: The app_location of this ApplicationLocationAvailabilityAppInfoAvailableLocations.
        :type app_location: LocationConstraints
        """

        self._app_location = app_location
