# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TraceRouteDiagnosticsDiagnosticsState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _1 = "1"
    _2 = "2"
    _3 = "3"
    _4 = "4"
    _5 = "5"
    _6 = "6"
    _7 = "7"
    def __init__(self):  # noqa: E501
        """TraceRouteDiagnosticsDiagnosticsState - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TraceRouteDiagnosticsDiagnosticsState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TraceRouteDiagnostics.diagnosticsState of this TraceRouteDiagnosticsDiagnosticsState.  # noqa: E501
        :rtype: TraceRouteDiagnosticsDiagnosticsState
        """
        return util.deserialize_model(dikt, cls)
